# Generated by Django 5.1.4 on 2025-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
